name: On push workflow with path and branch

on:
  push:
    branches:
      - main
    paths:
      - 'some/path/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 10
