name: Other workflow

on:
  push:
    branches:
      - 'non-existentt'
  workflow_dispatch:

jobs:
  create-pr:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repositoryyy
        uses: actions/checkout@v4
        with:
          ref: master
          fetch-depth: 0

      - name: Reset master branch
        run: |
          git fetch origin non-existent:non-existent
          git reset --hard non-existent

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e
        with:
          title: 'New PR'
          body: 'Some meaningless update'
          branch: 'non-existent'
          commit-message: 'no actual update'
          delete-branch: true
